// Generated by CoffeeScript 1.6.2
(function() {
  var app;

  app = angular.module('app', ['ngGrid']);

  app.controller('MyCtrl', function($scope, $timeout) {
    var pushIt;

    $scope.myData = [];
    pushIt = function() {
      $scope.myData.push({
        "engine": "Webkit",
        "browser": "Safari 3.0",
        "platform": "OSX.4+",
        "version": 522.1,
        "grade": "A",
        "date": new Date()
      });
      return $timeout(pushIt, 500);
    };
    pushIt();
    $scope.filterOptions = {
      filterText: '',
      useExternalFilter: true
    };
    $scope.totalServerItems = 0;
    $scope.pagingOptions = {
      pageSizes: [5, 10, 15],
      pageSize: 5,
      currentPage: 1
    };
    $scope.setPagingData = function(data, page, pageSize) {
      var pagedData;

      pagedData = data.slice((page - 1) * pageSize, page * pageSize);
      $scope.myData = pagedData;
      $scope.totalServerItems = data.length;
      if (!$scope.$$phase) {
        return $scope.$apply();
      }
    };
    $scope.getPagedDataAsync = function(pageSize, page, searchText) {
      setTimeout(function() {
        data;
        var ft;

        if (searchText) {
          ft = searchText.toLowerCase();
          return $http.get('largeLoad.json').success(function(largeLoad) {
            var data;

            data = largeLoad.filter(function(item) {
              return JSON.stringify(item).toLowerCase().indexOf(ft) !== -1;
            });
            return $scope.setPagingData(data, page, pageSize);
          });
        }
      }, 100);
      $scope.getPagedDataAsync($scope.pagingOptions.pageSize, $scope.pagingOptions.currentPage);
      return $scope.$watch('pagingOptions', function(newVal, oldVal) {
        if (newVal !== oldVal && newVal.currentPage !== oldVal.currentPage) {
          return $scope.getPagedDataAsync($scope.pagingOptions.pageSize, $scope.pagingOptions.currentPage, $scope.filterOptions.filterText);
        }
      }, true);
    };
    return $scope.gridOptions = {
      data: 'myData',
      columnDefs: [
        {
          field: 'engine',
          displayName: 'Engine'
        }, {
          field: 'browser',
          displayName: 'Browser'
        }, {
          field: 'platform',
          displayName: 'Platform'
        }, {
          field: 'version',
          displayName: 'Version',
          cellTemplate: 'cellTemplate.html'
        }, {
          field: 'grade',
          displayName: 'Grade'
        }, {
          field: 'date',
          displayName: 'Date'
        }
      ],
      showGroupPanel: true,
      enableCellSelection: true,
      enablePinning: true,
      enablePaging: true,
      showFooter: true
    };
  });

}).call(this);
